### PR TITLE
Add tzdata for windows

### PR DESCRIPTION
**Pull request by tibor-reiss**
https://github.com/ariebovenberg/whenever/issues/31

### CODE REVIEW

**Comment by ariebovenberg** [comment]
Also: change the line in the README that says "no dependencies" into "no third-party dependencies". It depends on backports and CPython maintained tzdata now.

**Comment by ariebovenberg** [comment]
Only thing left is to relax the version constraint. Who knows—maybe somebody wants to install an older tz db and we shouldn't be blocking them right?

**Comment by ariebovenberg** [comment]
Thanks @tibor-reiss for your contribution! 🚀 

I'll bring out a new release soon.

**Comment by tibor-reiss** [comment]
Morning @ariebovenberg, you were faster, thanks!
Nitpick: poetry.lock is out-of-date after relaxing the tzdata version.

**Comment by ariebovenberg** [comment]
> poetry.lock is out-of-date after relaxing the tzdata version. 

ah yes, I should add `poetry lock --check` to the CI to prevent this super common mistake.

**Pull request merged**
