### PR TITLE
Add from_py_date method to Date to compliment from_py_datetime on _DateTime

### PR DESCRIPTION
**Pull request by sherbang**
# Description

Simple addition of `Date.from_py_date`, matching the API of the datetime classes.

# Checklist

- [x] Build runs successfully
- [x] Docs updated

# Release checklist (maintainers only)

- [ ] Version updated in ``pyproject.toml``
- [ ] Version updated in ``src/whenever/__init__.py``
- [ ] Version updated in changelog
- [ ] Branch merged
- [ ] Tag created and pushed
- [ ] Published
- [ ] Github release created

### CODE REVIEW

**Comment by ariebovenberg** [comment]
@sherbang thanks for spotting this omission and taking the time for this PR 👍 

I've started the CI process, which will probably give an error on test coverage. Could you add a simple test in `test_date.py` to test this new method?

**Comment by ariebovenberg** [comment]
I also see that `isort` reported an error. You can run `make format` to run `isort` and `black`.

**Comment by sherbang** [comment]
I added a test, and fixed the formatting.  Thanks!

**Comment by ariebovenberg** [comment]
Thanks @sherbang for your contribution! 🚀

**Comment by ariebovenberg** [comment]
release 0.5.2 is now out with your addition!

**Pull request merged**
